### ISSUE TITLE
Auth0 API login says my account has been blocked (even though it hasn't) when trying to log in

### ISSUE THREAD

**Issue by Juliusvm** [auth0/auth0-flutter#161]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When trying to log in with username/password flow with the following code:

`
    final credentials = await auth0.api.login(
      audience: Environment.auth0Audience,
        usernameOrEmail: '**********',
        password: '********',
        connectionOrRealm: 'Username-Password-Authentication');
`

I get the following error message:
`Unhandled Exception: too_many_attempts: Your account has been blocked after multiple consecutive login attempts. We've sent you an email with instructions on how to unblock it.`

which I believe is invalid, because I got no email and I can still login with that account using the web authentication:

`
      final credentials = await auth0.webAuthentication().login(audience: Environment.auth0Audience, useEphemeralSession: true,
          redirectUrl: Environment.auth0RedirectUri);
`

I think the error code is wrong, and if it's not, it's quite misleading.

Full error trace:

`
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: too_many_attempts: Your account has been blocked after multiple consecutive login attempts. We've sent you an email with instructions on how to unblock it.
#0      MethodChannelAuth0FlutterAuth.invokeRequest (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_auth.dart:79:7)
<asynchronous suspension>
#1      MethodChannelAuth0FlutterAuth.login (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_auth.dart:27:9)
<asynchronous suspension>
#2      AppAuthService.signIn (package:mer_connect_app/state/auth_state_provider.dart:82:25)
<asynchronous suspension>
`

### Reproduction

1. Set up auth0 client: `Auth0 auth0 =  auth0 =  Auth0('domain', clientId);`
2. Try loggin in with `    final credentials = await auth0.api.login(
      audience: Environment.auth0Audience,
        usernameOrEmail: '**********',
        password: '********',
        connectionOrRealm: 'Username-Password-Authentication');`
3. See error `Unhandled Exception: too_many_attempts: Your account has been blocked after multiple consecutive login attempts. We've sent you an email with instructions on how to unblock it.`

### auth0_flutter version

1.0.0

### Flutter version

3.0.5

### Platform

iOS

### Platform version(s)

15.6.1

**Comment by Juliusvm** [comment]
Edit: 
Tried with a different `connectionOrRealm` and it worked. The error message I received wasn't very clear though.
