### ISSUE TITLE
Flutter 1.4.0 - Error: No named parameter with the name 'parameters'

### ISSUE THREAD

**Issue by cbhernan** [auth0/auth0-flutter#371]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`flutter build web`  is failing with an error message `Error: No named parameter with the name 'parameters'.`

### Reproduction

Reproduced on Sample App:

1. Download [sample app](https://github.com/auth0-samples/auth0-flutter-samples.git)
2. Update `pubspec.yaml` so that `auth0_flutter` uses version `1.4.0`
3. Run `flutter pub get`, run `flutter config --enable-web`
4. Run `flutter build web`

Same error encountered on my local project and GH Action. **Workaround is to downgrade**.

### Additional context

<details>
<summary>Full error logs</summary>

```
Target dart2js failed: ProcessException: Process exited abnormally:
../../../AppData/Local/Pub/Cache/hosted/pub.dev/auth0_flutter-1.4.0/lib/auth0_flutter_web.dart:73:13:
Error: No named parameter with the name 'parameters'.
            parameters: parameters),
            ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/auth0_flutter_platform_interface-1.2.1/lib/src/web/client_options.dart:108:3:
Info: Found this candidate, but the arguments don't match.
  ClientOptions(
  ^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/auth0_flutter-1.4.0/lib/src/web/extensions/client_options_extensions.dart:31:19:
Error: The getter 'parameters' isn't defined for the class 'ClientOptions'.
 - 'ClientOptions' is from 'package:auth0_flutter_platform_interface/src/web/client_options.dart'
 ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/auth0_flutter_platform_interface-1.2.1/lib/src/web/client_options.dart').
                  parameters)));
                  ^^^^^^^^^^
Error: Compilation failed.
  Command: C:\Users\506474\Downloads\flutter_windows_3.10.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
  C:\Users\506474\Downloads\flutter_windows_3.10.5-stable\flutter\bin\cache\dart-sdk\bin\snapshots\dart2js.dart.snapshot
  --platform-binaries=C:\Users\506474\Downloads\flutter_windows_3.10.5-stable\flutter\bin\cache\flutter_web_sdk\kernel --invoker=flutter_tool -Ddart.vm.product=true
  -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/54a7145303f0dd9d0f93424a2e124eb4abef5091/ --native-null-assertions
  --no-source-maps -o C:\Users\506474\sample\auth0-flutter-samples\sample\.dart_tool\flutter_build\8888fad93778815d38b8bdad056f294a\app.dill --packages=.dart_tool/package_config.json 
  --cfe-only C:\Users\506474\sample\auth0-flutter-samples\sample\.dart_tool\flutter_build\8888fad93778815d38b8bdad056f294a\main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:280:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:189:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:199:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                              9.1s
Exception: Failed to compile application for the Web.
```
</details>

### auth0_flutter version

1.4.0

### Flutter version

3.16.3

### Platform

Web

**Comment by Widcket** [comment]
Hi @cbhernan, thanks for raising this. We're aware of the issue: https://github.com/auth0/auth0-flutter/issues/368, and are working on a solution.

**Comment by cbhernan** [comment]
@Widcket Thank you for the update! My apologies for opening a duplicate issue!
